# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://robertcfoster.com
title: 'Top'
email: 'rcfoster@gmail.com'
author: Robert C. Foster
description: 'The personal website of statistician Robert C. Foster'
copyright: 'Copyright &copy; 2021 Robert C. Foster. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:

  - icon: Email
    title: Email
    url: mailto:rcfoster@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/robert-foster-07b645169/	
  - icon: CV
    title: CV
    url: https://rcfoster.github.io/cv/CV.pdf	
  - icon: github
    title: github
    url: https://github.com/rcfoster
  - icon: 'Google Scholar'
    title: 'google scholar'
    url: https://scholar.google.com/citations?user=Jn_dd0UAAAAJ

